import { getPublicKey } from 'https://esm.sh/@noble/secp256k1@1.7.1';
import { sha256 } from 'https://esm.sh/@noble/hashes@1.3.3/sha256';
import { ripemd160 } from 'https://esm.sh/@noble/hashes@1.3.3/ripemd160';
const $=id=>document.getElementById(id);const tabs=[...document.querySelectorAll('.tab')],panels={random:$('panel-random'),bitcoin:$('panel-bitcoin')};
const randomType=$('randomType'),lengthField=$('lengthField'),integerFields=$('integerFields'),byteLength=$('byteLength'),minValue=$('minValue'),maxValue=$('maxValue'),randomOutput=$('randomOutput'),privateKeyInput=$('privateKeyInput'),privateKeyOut=$('privateKeyOut'),publicKeyOut=$('publicKeyOut'),hash160Out=$('hash160Out'),wifOut=$('wifOut'),addressOut=$('addressOut'),explorerLink=$('explorerLink'),activityList=$('activityList');
let lastRandomHex='',currentWallet=null;const CURVE_N=BigInt('0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141'),LOG_KEY='cobra-public-address-log-v1';
for(const tab of tabs)tab.addEventListener('click',()=>{const selected=tab.dataset.tab;for(const item of tabs){const active=item===tab;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active))}for(const[key,panel]of Object.entries(panels)){const active=key===selected;panel.hidden=!active;panel.classList.toggle('active',active)}});
randomType.addEventListener('change',syncRandomFields);$('generateRandom').addEventListener('click',generateRandom);$('generateBitcoin').addEventListener('click',()=>deriveAndRender(generateValidPrivateKey(),true));$('deriveAddress').addEventListener('click',()=>deriveAndRender(normalizePrivateKey(privateKeyInput.value),true));$('useRandomAsKey').addEventListener('click',()=>{if(!lastRandomHex||lastRandomHex.length!==64){alert('Generate a 32-byte hexadecimal value in the Random Generator first.');return}deriveAndRender(normalizePrivateKey(lastRandomHex),true)});$('downloadRecovery').addEventListener('click',downloadRecoveryKit);$('clearLog').addEventListener('click',()=>{localStorage.removeItem(LOG_KEY);renderLog()});
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const target=$(button.dataset.copy),value=target?.textContent?.trim();if(!value||value==='—')return;await navigator.clipboard.writeText(value);const original=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=original,1200)}));
$('shareButton').addEventListener('click',async()=>{const shareData={title:'COBRA',text:'COBRA — Cryptographic Oracle for Bytes, Randomness & Addresses. Free Bitcoin randomness and address research tools.',url:window.location.href};if(navigator.share){try{await navigator.share(shareData)}catch(_){}}else{await navigator.clipboard.writeText(window.location.href);alert('Link copied to clipboard.')}});syncRandomFields();renderLog();
function syncRandomFields(){const type=randomType.value;integerFields.hidden=type!=='integer';lengthField.hidden=type==='integer'||type==='uuid'}
function generateRandom(){const type=randomType.value;let output='';if(type==='uuid')output=crypto.randomUUID();else if(type==='integer'){const min=Number(minValue.value),max=Number(maxValue.value);if(!Number.isSafeInteger(min)||!Number.isSafeInteger(max)||max<min){alert('Use safe integer values with maximum greater than or equal to minimum.');return}output=String(randomInteger(min,max))}else{const length=Math.max(1,Math.min(4096,Number(byteLength.value)||32));byteLength.value=String(length);const bytes=secureBytes(length);if(type==='hex'){output=bytesToHex(bytes);if(length===32)lastRandomHex=output}else output=[...bytes].join(' ')}randomOutput.textContent=output}
function randomInteger(min,max){const range=max-min+1;if(range<=0||range>0x100000000)throw new Error('Integer range must fit within 32 bits for unbiased generation.');const limit=Math.floor(0x100000000/range)*range,array=new Uint32Array(1);let value;do{crypto.getRandomValues(array);value=array[0]}while(value>=limit);return min+(value%range)}
function secureBytes(length){const bytes=new Uint8Array(length);for(let offset=0;offset<length;offset+=65536)crypto.getRandomValues(bytes.subarray(offset,Math.min(offset+65536,length)));return bytes}
function generateValidPrivateKey(){while(true){const bytes=secureBytes(32),value=BigInt(`0x${bytesToHex(bytes)}`);if(value>0n&&value<CURVE_N)return bytesToHex(bytes)}}
function normalizePrivateKey(value){const clean=String(value||'').trim().replace(/^0x/i,'').toLowerCase();if(!/^[0-9a-f]{64}$/.test(clean)){alert('Private key must be exactly 64 hexadecimal characters.');return null}const scalar=BigInt(`0x${clean}`);if(scalar<=0n||scalar>=CURVE_N){alert('Private key is outside the valid secp256k1 scalar range.');return null}return clean}
function deriveAndRender(privateHex,logAddress=false){if(!privateHex)return;try{const privateBytes=hexToBytes(privateHex),publicKey=getPublicKey(privateBytes,true),hash160=ripemd160(sha256(publicKey));const versioned=new Uint8Array(21);versioned[0]=0;versioned.set(hash160,1);const address=base58Check(versioned);const wifPayload=new Uint8Array(34);wifPayload[0]=0x80;wifPayload.set(privateBytes,1);wifPayload[33]=0x01;const wif=base58Check(wifPayload);currentWallet={privateKey:privateHex,wif,publicKey:bytesToHex(publicKey),hash160:bytesToHex(hash160),address,createdAt:new Date().toISOString(),type:'P2PKH mainnet'};privateKeyInput.value=privateHex;privateKeyOut.textContent=privateHex;publicKeyOut.textContent=currentWallet.publicKey;hash160Out.textContent=currentWallet.hash160;wifOut.textContent=wif;addressOut.textContent=address;explorerLink.href=`https://mempool.space/address/${address}`;explorerLink.classList.remove('disabled');if(logAddress)addPublicLog(address);renderLog()}catch(error){console.error(error);alert('Could not derive the address. Please try another valid private key.')}}
function addPublicLog(address){const log=getLog();if(!log.some(x=>x.address===address)){log.unshift({address,createdAt:new Date().toISOString(),type:'P2PKH mainnet'});localStorage.setItem(LOG_KEY,JSON.stringify(log.slice(0,50)))}}
function getLog(){try{return JSON.parse(localStorage.getItem(LOG_KEY)||'[]')}catch{return[]}}
function renderLog(){const log=getLog();if(!log.length){activityList.innerHTML='<div class="empty-state">Generate a Bitcoin address to begin your local activity log.</div>';return}activityList.innerHTML=log.map(item=>`<article><div><strong>${shorten(item.address)}</strong><span>${new Date(item.createdAt).toLocaleString()} · ${item.type}</span></div><a href="https://mempool.space/address/${item.address}" target="_blank" rel="noopener noreferrer">Explorer ↗</a></article>`).join('')}
function shorten(v){return v.length>22?`${v.slice(0,12)}…${v.slice(-8)}`:v}
function downloadRecoveryKit(){if(!currentWallet){alert('Generate or derive an address first.');return}const text=`COBRA RECOVERY KIT\nEducational / experimental use only\nCreated: ${currentWallet.createdAt}\nAddress type: ${currentWallet.type}\n\nBITCOIN ADDRESS\n${currentWallet.address}\n\nPRIVATE KEY — SECRET\n${currentWallet.privateKey}\n\nWIF — SECRET\n${currentWallet.wif}\n\nCOMPRESSED PUBLIC KEY\n${currentWallet.publicKey}\n\nHASH160\n${currentWallet.hash160}\n\nExplorer\nhttps://mempool.space/address/${currentWallet.address}\n\nWARNING\nAnyone with the private key or WIF can potentially control funds associated with this address. COBRA does not retain a backup. Store this file securely and do not use demonstration keys for material funds.\n`;const blob=new Blob([text],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`cobra-recovery-${currentWallet.address}.txt`;a.click();URL.revokeObjectURL(url)}
function base58Check(payload){const checksum=sha256(sha256(payload)).slice(0,4),full=new Uint8Array(payload.length+4);full.set(payload,0);full.set(checksum,payload.length);return base58Encode(full)}
function bytesToHex(bytes){return[...bytes].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function hexToBytes(hex){return Uint8Array.from(hex.match(/.{1,2}/g).map(byte=>parseInt(byte,16)))}
function base58Encode(bytes){const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let value=0n;for(const byte of bytes)value=(value<<8n)+BigInt(byte);let encoded='';while(value>0n){const remainder=Number(value%58n);encoded=alphabet[remainder]+encoded;value/=58n}for(const byte of bytes){if(byte===0)encoded='1'+encoded;else break}return encoded||'1'}