(()=>{
const dictionaries={
fr:{'COBRA // DOCUMENTATION':'COBRA // DOCUMENTATION','Understand the system.':'Comprendre le système.','Online or offline.':'En ligne ou hors ligne.','Method':'Méthode','Offline':'Hors ligne','Cold storage':'Stockage à froid','Offline transactions':'Transactions hors ligne','Terminal':'Terminal','Agents':'Agents','Future':'Avenir','1. Address derivation':'1. Dérivation d’adresse','2. COBRA Offline':'2. COBRA hors ligne','3. Cold storage':'3. Stockage à froid','4. Offline transactions with PSBT':'4. Transactions hors ligne avec PSBT','5. Terminal / Python':'5. Terminal / Python','6. Working with AI agents':'6. Travailler avec des agents IA','7. Storage of value & future hardware':'7. Réserve de valeur et futur matériel','References':'Références','Offline cryptographic lab':'Laboratoire cryptographique hors ligne','Random 256-bit value':'Valeur aléatoire 256 bits','Bitcoin derivation':'Dérivation Bitcoin','Offline transaction model':'Modèle de transaction hors ligne','Generate 32 bytes':'Générer 32 octets'},
es:{'Understand the system.':'Entiende el sistema.','Online or offline.':'En línea o sin conexión.','Method':'Método','Offline':'Sin conexión','Cold storage':'Almacenamiento en frío','Offline transactions':'Transacciones sin conexión','Terminal':'Terminal','Agents':'Agentes','Future':'Futuro','1. Address derivation':'1. Derivación de direcciones','2. COBRA Offline':'2. COBRA sin conexión','3. Cold storage':'3. Almacenamiento en frío','4. Offline transactions with PSBT':'4. Transacciones sin conexión con PSBT','5. Terminal / Python':'5. Terminal / Python','6. Working with AI agents':'6. Trabajar con agentes de IA','7. Storage of value & future hardware':'7. Reserva de valor y hardware futuro','References':'Referencias','Offline cryptographic lab':'Laboratorio criptográfico sin conexión','Random 256-bit value':'Valor aleatorio de 256 bits','Bitcoin derivation':'Derivación de Bitcoin','Offline transaction model':'Modelo de transacción sin conexión','Generate 32 bytes':'Generar 32 bytes'},
pt:{'Understand the system.':'Entenda o sistema.','Online or offline.':'Online ou offline.','Method':'Método','Offline':'Offline','Cold storage':'Armazenamento a frio','Offline transactions':'Transações offline','Terminal':'Terminal','Agents':'Agentes','Future':'Futuro','1. Address derivation':'1. Derivação de endereço','2. COBRA Offline':'2. COBRA Offline','3. Cold storage':'3. Armazenamento a frio','4. Offline transactions with PSBT':'4. Transações offline com PSBT','5. Terminal / Python':'5. Terminal / Python','6. Working with AI agents':'6. Trabalhando com agentes de IA','7. Storage of value & future hardware':'7. Reserva de valor e hardware futuro','References':'Referências','Offline cryptographic lab':'Laboratório criptográfico offline','Random 256-bit value':'Valor aleatório de 256 bits','Bitcoin derivation':'Derivação Bitcoin','Offline transaction model':'Modelo de transação offline','Generate 32 bytes':'Gerar 32 bytes'},
de:{'Understand the system.':'Das System verstehen.','Online or offline.':'Online oder offline.','Method':'Methode','Offline':'Offline','Cold storage':'Cold Storage','Offline transactions':'Offline-Transaktionen','Terminal':'Terminal','Agents':'Agenten','Future':'Zukunft','1. Address derivation':'1. Adressableitung','2. COBRA Offline':'2. COBRA Offline','3. Cold storage':'3. Cold Storage','4. Offline transactions with PSBT':'4. Offline-Transaktionen mit PSBT','5. Terminal / Python':'5. Terminal / Python','6. Working with AI agents':'6. Arbeiten mit KI-Agenten','7. Storage of value & future hardware':'7. Wertspeicherung & zukünftige Hardware','References':'Referenzen','Offline cryptographic lab':'Offline-Kryptolabor','Random 256-bit value':'Zufälliger 256-Bit-Wert','Bitcoin derivation':'Bitcoin-Ableitung','Offline transaction model':'Offline-Transaktionsmodell','Generate 32 bytes':'32 Bytes erzeugen'},
zh:{'Understand the system.':'理解系统。','Online or offline.':'在线或离线。','Method':'方法','Offline':'离线','Cold storage':'冷存储','Offline transactions':'离线交易','Terminal':'终端','Agents':'智能体','Future':'未来','1. Address derivation':'1. 地址派生','2. COBRA Offline':'2. COBRA 离线','3. Cold storage':'3. 冷存储','4. Offline transactions with PSBT':'4. 使用 PSBT 的离线交易','5. Terminal / Python':'5. 终端 / Python','6. Working with AI agents':'6. 与 AI 智能体协作','7. Storage of value & future hardware':'7. 价值存储与未来硬件','References':'参考资料','Offline cryptographic lab':'离线密码学实验室','Random 256-bit value':'256 位随机值','Bitcoin derivation':'比特币地址派生','Offline transaction model':'离线交易模型','Generate 32 bytes':'生成 32 字节'}};
const host=document.querySelector('.docs,.wrap');if(!host)return;
const bar=document.createElement('div');bar.style.cssText='position:fixed;right:18px;top:16px;z-index:9999';bar.innerHTML='<select id="docsLang" aria-label="Language" style="background:#090d0b;color:#dce6df;border:1px solid rgba(85,245,138,.3);border-radius:999px;padding:8px 12px;font:700 11px ui-monospace,monospace"><option value="en">EN</option><option value="fr">FR</option><option value="es">ES</option><option value="pt">PT</option><option value="de">DE</option><option value="zh">中文</option></select>';document.body.appendChild(bar);
const original=new WeakMap();const nodes=[...document.querySelectorAll('h1,h2,h3,p,a,button,strong,.badge,.status')];nodes.forEach(n=>original.set(n,n.textContent));
function apply(lang){document.documentElement.lang=lang==='zh'?'zh-CN':lang;const map=dictionaries[lang]||{};nodes.forEach(n=>{const base=original.get(n);const trimmed=base.trim();n.textContent=lang==='en'?base:(map[trimmed]?base.replace(trimmed,map[trimmed]):base)});localStorage.setItem('cobra-language',lang)}
const select=document.getElementById('docsLang');select.value=localStorage.getItem('cobra-language')||'en';select.addEventListener('change',e=>apply(e.target.value));apply(select.value);
})();